# Base configs
baseurl: "https://falkory220.github.io/Portfolio/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Art by Falkory"
subtitle: "A collection of art ive made!"
author: "Falkory"
header:
 title: "Art"
 subtitle: "by Falkory"
footer:
 name: "Hi, Im Falkory"
 bio: "I am a pixel artist with a focus on making art for MC mods and similar content."
web_design: "Falkory"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
#social_urls:
#  twitter: ""
#  instagram: ""
#  dribbble: ""
#  linkedin: ""
#  github: ""
